# SPDX-FileCopyrightText: 2024 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: CC0-1.0

name = "edge"
source = "github:bmFtZQ/edge-frfox"

[[configs]]
key = "svg.context-properties.content.enabled"
value = "true"
raw = true

[[configs]]
key = "layout.css.color-mix.enabled"
value = "true"
raw = true

[[configs]]
key = "layout.css.light-dark.enabled"
value = "true"
raw = true

[[configs]]
key = "widget.macos.native-context-menus"
value = "false"
raw = true

[[configs]]
key = "browser.tabs.tabMinWidth"
value = "66"
raw = true

[[configs]]
key = "browser.tabs.tabClipWidth"
value = "86"
raw = true
