# SPDX-FileCopyrightText: 2024 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: CC0-1.0

name = "shyfox"
source = "github:Naezr/ShyFox"

[[configs]]
key = "svg.context-properties.content.enabled"
value = "true"
raw = true

[[configs]]
key = "layout.css.has-selector.enabled"
value = "true"
raw = true

[[configs]]
key = "browser.urlbar.suggest.calculator"
value = "true"
raw = true

[[configs]]
key = "browser.urlbar.unitConversion.enabled"
value = "true"
raw = true

[[configs]]
key = "browser.urlbar.trimHttps"
value = "true"
raw = true

[[configs]]
key = "browser.urlbar.trimURLs"
value = "true"
raw = true

[[configs]]
key = "shyfox.disable.compact.unified.extensions"
value = "true"
raw = true
